### ISSUE TITLE
Run teamspeak as unprivileged user

### ISSUE THREAD

**Issue by jaltek** [overshard/docker-teamspeak#6] opened 2015-06-30 11:11 UTC
Hi,

just for the paranoid ones of us:
Although this app is running inside a container, Teamspeak should run as unprivileged user. 

https://forums.docker.com/t/root-user-or-non-root-user-inside-container/966/3
https://groups.google.com/forum/#!msg/docker-user/e9RkC4y-21E/JOZF8H-PfYsJ

What do you think?

**Comment by Nextgensource** [comment] 2015-11-03 06:21
a little late, but I just did this this myself(its really easy). Pull [this](https://github.com/Nextgensource/docker-teamspeak) if you still need it.

**Comment by overshard** [comment] 2015-11-10 18:50
I agree this should be done, if anyone wants to do a pull request for it I'll merge.

**Comment by XanderXAJ** [comment] 2016-01-30 15:19
It looks like this was merged with 78f2f2dcb35489b2ebbbf0e239ba3d55d9ad083c, so this can be closed now?

**Comment by overshard** [comment] 2016-02-03 23:48
I've reverting it due to the update not functioning properly, so this is still an issue.

**Comment by overshard** [comment] 2016-02-04 00:23
The issue is the files we store in /data and on the primary machine /mnt/teamspeak aren't properly owned by the teamspeak user. This causes the system to break at the moment.

**Comment by overshard** [comment] 2016-05-18 22:31
This is fixed in the latest pull request, it's working great now!

**Closed by overshard** 2016-05-18 22:31 UTC
